{{- if .Values.ingress.enabled -}}
{{- $fullName := include "k8s-ready-servcie.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: {{ $fullName }}
  labels:
    app: {{ template "k8s-ready-servcie.name" . }}
    chart: {{ template "k8s-ready-servcie.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "k8s-ready-servcie.fullname" . }}
          servicePort: {{ .Values.service.port }}
        path: /.*
{{- end }}
