apiVersion: v1
kind: Service
metadata:
  name: {{ template "admission-webhook.fullname" . }}
  labels:
    app: {{ template "admission-webhook.name" . }}
    chart: {{ template "admission-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    auth.istio.io/{{ .Values.service.port }}: NONE
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "admission-webhook.name" . }}
    release: {{ .Release.Name }}
