/*
My awesome controller
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// CakeListerExpansion allows custom methods to be added to
// CakeLister.
type CakeListerExpansion interface{}

// CakeNamespaceListerExpansion allows custom methods to be added to
// CakeNamespaceLister.
type CakeNamespaceListerExpansion interface{}
