/*
My awesome controller
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/abbi-gaurav/go-projects/my-awesome-controller/pkg/client/clientset/versioned"
	awesomev1 "github.com/abbi-gaurav/go-projects/my-awesome-controller/pkg/client/clientset/versioned/typed/awesome.controller.io/v1"
	fakeawesomev1 "github.com/abbi-gaurav/go-projects/my-awesome-controller/pkg/client/clientset/versioned/typed/awesome.controller.io/v1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

var _ clientset.Interface = &Clientset{}

// AwesomeV1 retrieves the AwesomeV1Client
func (c *Clientset) AwesomeV1() awesomev1.AwesomeV1Interface {
	return &fakeawesomev1.FakeAwesomeV1{Fake: &c.Fake}
}

// Awesome retrieves the AwesomeV1Client
func (c *Clientset) Awesome() awesomev1.AwesomeV1Interface {
	return &fakeawesomev1.FakeAwesomeV1{Fake: &c.Fake}
}
