/*
My awesome controller
*/
// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	awesomev1 "github.com/abbi-gaurav/go-projects/my-awesome-controller/pkg/client/clientset/versioned/typed/awesome.controller.io/v1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	AwesomeV1() awesomev1.AwesomeV1Interface
	// Deprecated: please explicitly pick a version if possible.
	Awesome() awesomev1.AwesomeV1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	awesomeV1 *awesomev1.AwesomeV1Client
}

// AwesomeV1 retrieves the AwesomeV1Client
func (c *Clientset) AwesomeV1() awesomev1.AwesomeV1Interface {
	return c.awesomeV1
}

// Deprecated: Awesome retrieves the default version of AwesomeClient.
// Please explicitly pick a version.
func (c *Clientset) Awesome() awesomev1.AwesomeV1Interface {
	return c.awesomeV1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.awesomeV1, err = awesomev1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.awesomeV1 = awesomev1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.awesomeV1 = awesomev1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
