---
apiVersion: v1
kind: Service
metadata:
  name: dummy-subscriber
  labels:
    app: dummy-subscriber
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: dummy-subscriber
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dummy-subscriber
  labels:
    app: dummy-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-subscriber
  template:
    metadata:
      labels:
        app: dummy-subscriber
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: dummy-subscriber
          image: gabbi/dummy-subscriber:0.1
          imagePullPolicy: IfNotPresent
          args:
            - --port=8080
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
            limits:
              memory: "32M"
