/*
My awesome controller
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/abbi-gaurav/go-learning-projects/my-awesome-controller/pkg/apis/awesome.controller.io/v1"
	"github.com/abbi-gaurav/go-learning-projects/my-awesome-controller/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type AwesomeV1Interface interface {
	RESTClient() rest.Interface
	CakesGetter
}

// AwesomeV1Client is used to interact with features provided by the awesome.controller.io group.
type AwesomeV1Client struct {
	restClient rest.Interface
}

func (c *AwesomeV1Client) Cakes(namespace string) CakeInterface {
	return newCakes(c, namespace)
}

// NewForConfig creates a new AwesomeV1Client for the given config.
func NewForConfig(c *rest.Config) (*AwesomeV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &AwesomeV1Client{client}, nil
}

// NewForConfigOrDie creates a new AwesomeV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AwesomeV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AwesomeV1Client for the given RESTClient.
func New(c rest.Interface) *AwesomeV1Client {
	return &AwesomeV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AwesomeV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
