apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sloops.ships.gaurav.io
spec:
  group: ships.gaurav.io
  names:
    kind: Sloop
    plural: sloops
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            rig:
              type: string
          required:
          - rig
          type: object
        status:
          properties:
            configured:
              type: boolean
            update:
              type: boolean
          required:
          - configured
          - update
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
