apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cakes.awesome.controller.io
spec:
  group: awesome.controller.io
  version: v1
  names:
    kind: Cake
    plural: cakes
    singular: cake
    shortNames:
    - ck
  scope: Namespaced
